### ISSUE TITLE
Read Backup --> cp error reading '...': Function not implemented

### ISSUE THREAD

**Issue by pcace** [mbrt/ruplicity-fuse#7]
Hi,

i cannot copy any data from a mounted backup. 
Mounting it works:
` ruplicity-fuse /mnt/backup_fuse/ /mnt/gdrive/Backup/
INFO - Loading backup from path "/mnt/gdrive/Backup/"
INFO - Mounting /mnt/backup_fuse/
DEBUG - INIT(1)   kernel: ABI 7.26, flags 0x1ffffb, max readahead 131072
DEBUG - INIT(1) response: ABI 7.8, flags 0x31, max readahead 131072, max write 16777216
`
i can see files on the mounted backup:
`ls /mnt/backup_fuse/2018-10-06_18-31-03/etc/
acpi                    dpkg             ld.so.conf      opt            sensors.d
adduser.conf            drirc            ld.so.conf.d    os-release     services
adjtime                 emacs            letsencrypt     PackageKit     sgml
aliases                 environment      libao.conf      pam.conf       shadow
aliases.db              fail2ban         libaudit.conf   pam.d          shadow-
alternatives            firefox-esr      libnl-3         papersize      shells
.
.
.`

but if i try to copy anything from there, i get this:

`cp /mnt/backup_fuse/2018-10-06_18-31-03/etc/dhcp/dhclient.conf ~/
cp: error reading '/mnt/backup_fuse/2018-10-06_18-31-03/etc/dhcp/dhclient.conf': Function not implemented
`

Any Idea what to do here?

Thank you so much!!

**Comment by mbrt** [comment]
Hey there,

Unfortunately the read functionality has not been completed in the main
ruplicity <https://github.com/mbrt/ruplicity> repository.
There is a work in progress branch
<https://github.com/mbrt/ruplicity/tree/read_file> only, at the moment. I'm
not sure yet when I have time to finish it.

Perhaps I should put a disclaimer in the README.
